In [1]:
# Part a)
# Column-minimum method
capacity = [5,8,7]
demand = [3,6,6,5]
cost = [[4,5,2,7],[5,8,6,2],[8,9,4,3]] # list of list

n = 3 # number of rows/sources
m = 4 # number of columns/sinks

if sum(capacity) < sum(demand):
    print ("Cannot fulfilled all demand !")
else:
    
    import numpy as np
    transport = np.zeros((n,m)) # matrix

    import copy
    rc = copy.deepcopy(capacity)
    rd = copy.deepcopy(demand)
    tc = 0

    for j in range(m): #iterate over sinks

        cost_col = [list[j] for list in cost] #generate a list of cost unit from each source to sink j
        cost_col = [(c,idx) for idx,c in enumerate(cost_col)] #include index of source with the corresponding cost unit
        ranked_sources = [x[1] for x in sorted(cost_col)] #rank sources in ascending order of cost unit list

        temp_index = 0 #iterate from left to right of the cost unit list
        while (rd[j] > 0) and (temp_index < n): 
            current_source = ranked_sources[temp_index]
            if rc[current_source] > 0 :
                transport[current_source, j] = min(rc[current_source], rd[j])
                rd[j]                -= transport[current_source, j] #calculate remaining demand
                rc[current_source]   -= transport[current_source, j] #calculate remaining capacity
                tc                   += transport[current_source, j] * cost[current_source][j]
            else: temp_index += 1

    print("Transportation quantities: ")
    print(transport)
    print("Total cost: "+str(tc))

Transportation quantities: 
[[3. 2. 0. 0.]
 [0. 4. 0. 4.]
 [0. 0. 6. 1.]]
Total cost: 89.0


In [2]:
# Matrix-minimum method
capacity = [5,8,7]
demand = [3,6,6,5]
cost = [[4,5,2,7],[5,8,6,2],[8,9,4,3]] # list of list

n = 3 # number of rows/sources
m = 4 # number of columns/sinks

if sum(capacity) < sum(demand):
    print ("Cannot fulfilled all demand !")
else:
    
    import numpy as np
    transport = np.zeros((n,m)) # matrix


    import copy
    rc = copy.deepcopy(capacity)
    rd = copy.deepcopy(demand)
    tc = 0
    
    temp_cost = []
    for i in range(n): #iterate over sources
        for j in range(m): #iterate over sinks
            temp_cost.append((cost[i][j], (i, j)))
    ranked_connections = [x[1] for x in sorted(temp_cost)]        
    
    temp_index = 0 #iterate from left to right of the cost unit list    
    while sum(rd) > 0:    
        current_source = ranked_connections[temp_index][0]
        current_sink = ranked_connections[temp_index][1]
        
        if (rd[current_sink] > 0) and (rc[current_source] > 0):
            transport[current_source, current_sink] = min(rc[current_source], rd[current_sink])
            rd[current_sink]        -= transport[current_source, current_sink] #calculate remaining demand
            rc[current_source]      -= transport[current_source, current_sink] #calculate remaining capacity
            tc                      += transport[current_source, current_sink] * cost[current_source][current_sink]            
        else:
            temp_index += 1
            continue

    print("Transportation quantities: ")
    print(transport)
    print("Total cost: "+str(tc))


Transportation quantities: 
[[0. 0. 5. 0.]
 [3. 0. 0. 5.]
 [0. 6. 1. 0.]]
Total cost: 93.0
